version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - build/*
            - node_modules/**
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ad:2a:15:0d:e9:94:2b:04:6a:ba:f8:e4:e5:53:f0:73"
      - attach_workspace:
          at: ./
      - run:
          name: git login
          command: |
            git config --global user.email "thomascarli@gmail.com"
            git config --global user.name "CI"
      - run:
          name: deploy gh-pages
          command: npm run deploy

workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy:
          requires:
           - build
          filters:
            branches:
              only: 
                - master
